In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("reviews.csv")

In [3]:
data

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2384,25218143,2015-01-09,14385014,Ivan,it's a wonderful trip experience. I didn't exc...
1,2384,28475392,2015-03-24,16241178,Namhaitou,This is my first trip using Airbnb. I was a li...
2,2384,30273263,2015-04-19,26101401,Patrick,The reservation was canceled 80 days before ar...
3,2384,30974202,2015-04-30,26247321,Cristina,Sólo puedo decir cosas buenas de Rebecca. La h...
4,2384,31363208,2015-05-04,31293837,SuJung,Rebecca was an absolutely wonderful host.\r<br...
...,...,...,...,...,...,...
345934,754405301565810013,769657411844112955,2022-11-27,470882354,Sarvesh,Good value for money
345935,754405301565810013,775390607429906258,2022-12-05,11230541,Kent,"Pros: good location, comfortable bed, TV with ..."
345936,754405301565810013,781193082361202358,2022-12-13,264975993,Ayodeji,Daniel is a responsive host but needs to fix a...
345937,773214911162646829,779795379056048000,2022-12-11,42157002,Joe,Tim was the most gracious and hospitable host....
345938,774729726589280791,779740405077624533,2022-12-11,427107548,Thad,Very beautiful property! Would come back again!